import { Component, OnInit } from '@angular/core';
import { ColorItem } from '../models/coloritem';
import { ColorItemX } from '../models/coloritem';
import { trigger,state,style,transition,animate,keyframes } from '@angular/animations';

@Component({
  selector: 'app-html-colors',
  templateUrl: './html-colors.component.html',
  styleUrls: ['./html-colors.component.scss'],
  animations: [
    trigger('myAwesomeAnimation', [
      state('small', style({
          transform: 'scale(1)',
      })),
      state('large', style({
          transform: 'scale(1)',
      })),
      /*
      transition('small <=> large', animate(1000, keyframes([
        style({opacity: 0, transform: 'perspective(800px) rotateX(-90deg);', offset: 0.0}),
        style({opacity: 1, transform: 'perspective(800px) rotateX(50deg);', offset: 0.5}),
        style({opacity: 1, transform: 'perspective(800px) rotateX(0deg);', offset: 1.0})
      ]))),
      */
       // we can use it  origin:'50% 0%;'
      transition('small <=> large', animate('300ms ease-in', keyframes([
        style({opacity: 1, transform: 'translateY(35px)',  offset: 0.0}),
        style({opacity: 1, transform: 'translateY(0)',     offset: 1.0})
      ]))),
  ]),
  ]
})
export class HtmlColorsComponent implements OnInit {

  title: string = "HTML Colors";
  
  colorArray: ColorItemX[] = [
    {name: 'Gainsboro 		    ' , color: '#DCDCDC', state:'small'},
    {name: 'Lightgray			' , color: '#D3D3D3', state:'small'},
    {name: 'Silver  			' , color: '#C0C0C0', state:'small'},
    {name: 'Darkgray			' , color: '#A9A9A9', state:'small'},
    {name: 'Gray				' , color: '#808080', state:'small'},
    {name: 'Dimgray				' , color: '#696969', state:'small'},
    {name: 'Lightslategray		' , color: '#778899', state:'small'},
    {name: 'Slategray			' , color: '#708090', state:'small'},
    {name: 'Darkslategray		' , color: '#2F4F4F', state:'small'},
    {name: 'Black				' , color: '#000000', state:'small'},
    {name: 'Cornsilk			' , color: '#FFF8DC', state:'small'},
    {name: 'Blanchedalmond		' , color: '#FFEBCD', state:'small'},
    {name: 'Bisque				' , color: '#FFE4C4', state:'small'},
    {name: 'Navajowhite			' , color: '#FFDEAD', state:'small'},
    {name: 'Wheat				' , color: '#F5DEB3', state:'small'},
    {name: 'Burlywood			' , color: '#DEB887', state:'small'},
    {name: 'Tan					' , color: '#D2B48C', state:'small'},
    {name: 'Rosybrown			' , color: '#BC8F8F', state:'small'},
    {name: 'Sandybrown			' , color: '#F4A460', state:'small'},
    {name: 'Goldenrod			' , color: '#DAA520', state:'small'},
    {name: 'Darkgoldenrod		' , color: '#B8860B', state:'small'},
    {name: 'Peru				' , color: '#CD853F', state:'small'},
    {name: 'Chocolate			' , color: '#D2691E', state:'small'},
    {name: 'Saddlebrown			' , color: '#8B4513', state:'small'},
    {name: 'Sienna				' , color: '#A0522D', state:'small'},
    {name: 'Brown				' , color: '#A52A2A', state:'small'},
    {name: 'Maroon				' , color: '#800000', state:'small'},
    {name: 'Indianred			' , color: '#CD5C5C', state:'small'},
    {name: 'Lightcoral			' , color: '#F08080', state:'small'},
    {name: 'Salmon				' , color: '#FA8072', state:'small'},
    {name: 'Darksalmon			' , color: '#E9967A', state:'small'},
    {name: 'Lightsalmon			' , color: '#FFA07A', state:'small'},
    {name: 'Crimson				' , color: '#DC143C', state:'small'},
    {name: 'Red					' , color: '#FF0000', state:'small'},
    {name: 'Firebrick			' , color: '#B22222', state:'small'},
    {name: 'Darkred				' , color: '#8B0000', state:'small'},
    {name: 'Pink				' , color: '#FFC0CB', state:'small'},
    {name: 'Lightpink			' , color: '#FFB6C1', state:'small'},
    {name: 'Hotpink				' , color: '#FF69B4', state:'small'},
    {name: 'Deeppink			' , color: '#FF1493', state:'small'},
    {name: 'Mediumvioletred		' , color: '#C71585', state:'small'},
    {name: 'Palevioletred		' , color: '#DB7093', state:'small'},
    {name: 'Lightsalmon			' , color: '#FFA07A', state:'small'},
    {name: 'Coral				' , color: '#FF7F50', state:'small'},
    {name: 'Tomato				' , color: '#FF6347', state:'small'},
    {name: 'Orangered			' , color: '#FF4500', state:'small'},
    {name: 'Darkorange			' , color: '#FF8C00', state:'small'},
    {name: 'Orange				' , color: '#FFA500', state:'small'},
    {name: 'Gold				' , color: '#FFD700', state:'small'},
    {name: 'Yellow				' , color: '#FFFF00', state:'small'},
    {name: 'Lightyellow			' , color: '#FFFFE0', state:'small'},
    {name: 'Lemonchiffon		' , color: '#FFFACD', state:'small'},
    {name: 'Lightgoldenrodyellow' , color: '#FAFAD2', state:'small'},
    {name: 'Papayawhip			' , color: '#FFEFD5', state:'small'},
    {name: 'Moccasin			' , color: '#FFE4B5', state:'small'},
    {name: 'Peachpuff			' , color: '#FFDAB9', state:'small'},
    {name: 'Palegoldenrod		' , color: '#EEE8AA', state:'small'},
    {name: 'Khaki				' , color: '#F0E68C', state:'small'},
    {name: 'Darkkhaki			' , color: '#BDB76B', state:'small'},
    {name: 'Greenyellow			' , color: '#ADFF2F', state:'small'},
    {name: 'Chartreuse			' , color: '#7FFF00', state:'small'},
    {name: 'Lawngreen			' , color: '#7CFC00', state:'small'},
    {name: 'Lime				' , color: '#00FF00', state:'small'},
    {name: 'Limegreen			' , color: '#32CD32', state:'small'},
    {name: 'Palegreen			' , color: '#98FB98', state:'small'},
    {name: 'Lightgreen			' , color: '#90EE90', state:'small'},
    {name: 'Mediumspringgreen	' , color: '#00FA9A', state:'small'},
    {name: 'Springgreen			' , color: '#00FF7F', state:'small'},
    {name: 'Mediumseagreen		' , color: '#3CB371', state:'small'},
    {name: 'Seagreen			' , color: '#2E8B57', state:'small'},
    {name: 'Forestgreen			' , color: '#228B22', state:'small'},
    {name: 'Green				' , color: '#008000', state:'small'},
    {name: 'Darkgreen			' , color: '#006400', state:'small'},
    {name: 'Yellowgreen			' , color: '#9ACD32', state:'small'},
    {name: 'Olivedrab			' , color: '#6B8E23', state:'small'},
    {name: 'Olive				' , color: '#808000', state:'small'},
    {name: 'Darkolivegreen		' , color: '#556B2F', state:'small'},
    {name: 'Mediumaquamarine	' , color: '#66CDAA', state:'small'},
    {name: 'Darkseagreen		' , color: '#8FBC8B', state:'small'},
    {name: 'Lightseagreen		' , color: '#20B2AA', state:'small'},
    {name: 'Darkcyan			' , color: '#008B8B', state:'small'},
    {name: 'Teal				' , color: '#008080', state:'small'},
    {name: 'Lavender			' , color: '#E6E6FA', state:'small'},
    {name: 'Thistle				' , color: '#D8BFD8', state:'small'},
    {name: 'Plum				' , color: '#DDA0DD', state:'small'},
    {name: 'Violet				' , color: '#EE82EE', state:'small'},
    {name: 'Orchid				' , color: '#DA70D6', state:'small'},
    {name: 'Fuchsia				' , color: '#FF00FF', state:'small'},
    {name: 'Magenta				' , color: '#FF00FF', state:'small'},
    {name: 'Mediumorchid		' , color: '#BA55D3', state:'small'},
    {name: 'Mediumpurple		' , color: '#9370DB', state:'small'},
    {name: 'Rabeccapurple		' , color: '#663399', state:'small'},
    {name: 'Blueviolet			' , color: '#8A2BE2', state:'small'},
    {name: 'Darkviolet			' , color: '#9400D3', state:'small'},
    {name: 'Darkorchid			' , color: '#9932CC', state:'small'},
    {name: 'Darkmagenta			' , color: '#8B008B', state:'small'},
    {name: 'Purple				' , color: '#800080', state:'small'},
    {name: 'Indigo				' , color: '#4B0082', state:'small'},
    {name: 'Slateblue			' , color: '#6A5ACD', state:'small'},
    {name: 'Darkslateblue		' , color: '#483D8B', state:'small'},
    {name: 'Mediumslateblue		' , color: '#7B68EE', state:'small'},
    {name: 'Aqua				' , color: '#00FFFF', state:'small'},
    {name: 'Cyan				' , color: '#00FFFF', state:'small'},
    {name: 'Lightcyan			' , color: '#E0FFFF', state:'small'},
    {name: 'Paleturquoise		' , color: '#AFEEEE', state:'small'},
    {name: 'Aquamarine			' , color: '#7FFFD4', state:'small'},
    {name: 'Turquoise			' , color: '#40E0D0', state:'small'},
    {name: 'Mediumturquoise		' , color: '#48D1CC', state:'small'},
    {name: 'Darkturquoise		' , color: '#00CED1', state:'small'},
    {name: 'Cadetblue			' , color: '#5F9EA0', state:'small'},
    {name: 'Steelblue			' , color: '#4682B4', state:'small'},
    {name: 'Lightsteelblue		' , color: '#B0C4DE', state:'small'},
    {name: 'Powderblue			' , color: '#B0E0E6', state:'small'},
    {name: 'Lightblue			' , color: '#ADD8E6', state:'small'},
    {name: 'Skyblue				' , color: '#87CEEB', state:'small'},
    {name: 'Lightskyblue		' , color: '#87CEFA', state:'small'},
    {name: 'Deepskyblue			' , color: '#00BFFF', state:'small'},
    {name: 'Dodgerblue			' , color: '#1E90FF', state:'small'},
    {name: 'Cornflowerblue		' , color: '#6495ED', state:'small'},
    {name: 'Mediumslateblue		' , color: '#7B68EE', state:'small'},
    {name: 'Royalblue			' , color: '#4169E1', state:'small'},
    {name: 'Blue				' , color: '#0000FF', state:'small'},
    {name: 'Mediumblue			' , color: '#0000CD', state:'small'},
    {name: 'Darkblue			' , color: '#00008B', state:'small'},
    {name: 'Navy				' , color: '#000080', state:'small'},
    {name: 'Midnightblue		' , color: '#191970', state:'small'},
    {name: 'White				' , color: '#FFFFFF', state:'small'},
    {name: 'Snow				' , color: '#FFFAFA', state:'small'},
    {name: 'Honeydew			' , color: '#F0FFF0', state:'small'},
    {name: 'Mintcream			' , color: '#F5FFFA', state:'small'},
    {name: 'Azure				' , color: '#F0FFFF', state:'small'},
    {name: 'Aliceblue			' , color: '#F0F8FF', state:'small'},
    {name: 'Chostwhite			' , color: '#F8F8FF', state:'small'},
    {name: 'Whitesmoke			' , color: '#F5F5F5', state:'small'},
    {name: 'Seashell			' , color: '#FFF5EE', state:'small'},
    {name: 'Beige				' , color: '#F5F5DC', state:'small'},
    {name: 'Oldlace				' , color: '#FDF5E6', state:'small'},
    {name: 'Floralwhite			' , color: '#FFFAF0', state:'small'},
    {name: 'Ivory				' , color: '#FFFFF0', state:'small'},
    {name: 'Antiquewhite		' , color: '#FAEBD7', state:'small'},
    {name: 'Linen				' , color: '#FAF0E6', state:'small'},
    {name: 'Lavenderblush		' , color: '#FFF0F5', state:'small'},
    {name: 'Mistyrose			' , color: '#FFE4E1', state:'small'}    
  ];

  constructor() { }

  ngOnInit() {
  }

  animateMe(ind: any) {
    this.colorArray[ind].state = (this.colorArray[ind].state === 'small' ? 'large' : 'small');
    //this.state = (this.state === 'small' ? 'large' : 'small');
  }
}
