import { Component, OnInit } from '@angular/core';
import { ColorItem } from '../models/coloritem';

@Component({
  selector: 'app-html-colors',
  templateUrl: './html-colors.component.html',
  styleUrls: ['./html-colors.component.scss']
})
export class HtmlColorsComponent implements OnInit {

  title: string = "HTML Colors";
  
  colorArray: ColorItem[] = [
    {name: 'Gainsboro 		    ' , color: '#DCDCDC'},
    {name: 'Lightgray			' , color: '#D3D3D3'},
    {name: 'Silver  			' , color: '#C0C0C0'},
    {name: 'Darkgray			' , color: '#A9A9A9'},
    {name: 'Gray				' , color: '#808080'},
    {name: 'Dimgray				' , color: '#696969'},
    {name: 'Lightslategray		' , color: '#778899'},
    {name: 'Slategray			' , color: '#708090'},
    {name: 'Darkslategray		' , color: '#2F4F4F'},
    {name: 'Black				' , color: '#000000'},
    {name: 'Cornsilk			' , color: '#FFF8DC'},
    {name: 'Blanchedalmond		' , color: '#FFEBCD'},
    {name: 'Bisque				' , color: '#FFE4C4'},
    {name: 'Navajowhite			' , color: '#FFDEAD'},
    {name: 'Wheat				' , color: '#F5DEB3'},
    {name: 'Burlywood			' , color: '#DEB887'},
    {name: 'Tan					' , color: '#D2B48C'},
    {name: 'Rosybrown			' , color: '#BC8F8F'},
    {name: 'Sandybrown			' , color: '#F4A460'},
    {name: 'Goldenrod			' , color: '#DAA520'},
    {name: 'Darkgoldenrod		' , color: '#B8860B'},
    {name: 'Peru				' , color: '#CD853F'},
    {name: 'Chocolate			' , color: '#D2691E'},
    {name: 'Saddlebrown			' , color: '#8B4513'},
    {name: 'Sienna				' , color: '#A0522D'},
    {name: 'Brown				' , color: '#A52A2A'},
    {name: 'Maroon				' , color: '#800000'},
    {name: 'Indianred			' , color: '#CD5C5C'},
    {name: 'Lightcoral			' , color: '#F08080'},
    {name: 'Salmon				' , color: '#FA8072'},
    {name: 'Darksalmon			' , color: '#E9967A'},
    {name: 'Lightsalmon			' , color: '#FFA07A'},
    {name: 'Crimson				' , color: '#DC143C'},
    {name: 'Red					' , color: '#FF0000'},
    {name: 'Firebrick			' , color: '#B22222'},
    {name: 'Darkred				' , color: '#8B0000'},
    {name: 'Pink				' , color: '#FFC0CB'},
    {name: 'Lightpink			' , color: '#FFB6C1'},
    {name: 'Hotpink				' , color: '#FF69B4'},
    {name: 'Deeppink			' , color: '#FF1493'},
    {name: 'Mediumvioletred		' , color: '#C71585'},
    {name: 'Palevioletred		' , color: '#DB7093'},
    {name: 'Lightsalmon			' , color: '#FFA07A'},
    {name: 'Coral				' , color: '#FF7F50'},
    {name: 'Tomato				' , color: '#FF6347'},
    {name: 'Orangered			' , color: '#FF4500'},
    {name: 'Darkorange			' , color: '#FF8C00'},
    {name: 'Orange				' , color: '#FFA500'},
    {name: 'Gold				' , color: '#FFD700'},
    {name: 'Yellow				' , color: '#FFFF00'},
    {name: 'Lightyellow			' , color: '#FFFFE0'},
    {name: 'Lemonchiffon		' , color: '#FFFACD'},
    {name: 'Lightgoldenrodyellow' , color: '#FAFAD2'},
    {name: 'Papayawhip			' , color: '#FFEFD5'},
    {name: 'Moccasin			' , color: '#FFE4B5'},
    {name: 'Peachpuff			' , color: '#FFDAB9'},
    {name: 'Palegoldenrod		' , color: '#EEE8AA'},
    {name: 'Khaki				' , color: '#F0E68C'},
    {name: 'Darkkhaki			' , color: '#BDB76B'},
    {name: 'Greenyellow			' , color: '#ADFF2F'},
    {name: 'Chartreuse			' , color: '#7FFF00'},
    {name: 'Lawngreen			' , color: '#7CFC00'},
    {name: 'Lime				' , color: '#00FF00'},
    {name: 'Limegreen			' , color: '#32CD32'},
    {name: 'Palegreen			' , color: '#98FB98'},
    {name: 'Lightgreen			' , color: '#90EE90'},
    {name: 'Mediumspringgreen	' , color: '#00FA9A'},
    {name: 'Springgreen			' , color: '#00FF7F'},
    {name: 'Mediumseagreen		' , color: '#3CB371'},
    {name: 'Seagreen			' , color: '#2E8B57'},
    {name: 'Forestgreen			' , color: '#228B22'},
    {name: 'Green				' , color: '#008000'},
    {name: 'Darkgreen			' , color: '#006400'},
    {name: 'Yellowgreen			' , color: '#9ACD32'},
    {name: 'Olivedrab			' , color: '#6B8E23'},
    {name: 'Olive				' , color: '#808000'},
    {name: 'Darkolivegreen		' , color: '#556B2F'},
    {name: 'Mediumaquamarine	' , color: '#66CDAA'},
    {name: 'Darkseagreen		' , color: '#8FBC8B'},
    {name: 'Lightseagreen		' , color: '#20B2AA'},
    {name: 'Darkcyan			' , color: '#008B8B'},
    {name: 'Teal				' , color: '#008080'},
    {name: 'Lavender			' , color: '#E6E6FA'},
    {name: 'Thistle				' , color: '#D8BFD8'},
    {name: 'Plum				' , color: '#DDA0DD'},
    {name: 'Violet				' , color: '#EE82EE'},
    {name: 'Orchid				' , color: '#DA70D6'},
    {name: 'Fuchsia				' , color: '#FF00FF'},
    {name: 'Magenta				' , color: '#FF00FF'},
    {name: 'Mediumorchid		' , color: '#BA55D3'},
    {name: 'Mediumpurple		' , color: '#9370DB'},
    {name: 'Rabeccapurple		' , color: '#663399'},
    {name: 'Blueviolet			' , color: '#8A2BE2'},
    {name: 'Darkviolet			' , color: '#9400D3'},
    {name: 'Darkorchid			' , color: '#9932CC'},
    {name: 'Darkmagenta			' , color: '#8B008B'},
    {name: 'Purple				' , color: '#800080'},
    {name: 'Indigo				' , color: '#4B0082'},
    {name: 'Slateblue			' , color: '#6A5ACD'},
    {name: 'Darkslateblue		' , color: '#483D8B'},
    {name: 'Mediumslateblue		' , color: '#7B68EE'},
    {name: 'Aqua				' , color: '#00FFFF'},
    {name: 'Cyan				' , color: '#00FFFF'},
    {name: 'Lightcyan			' , color: '#E0FFFF'},
    {name: 'Paleturquoise		' , color: '#AFEEEE'},
    {name: 'Aquamarine			' , color: '#7FFFD4'},
    {name: 'Turquoise			' , color: '#40E0D0'},
    {name: 'Mediumturquoise		' , color: '#48D1CC'},
    {name: 'Darkturquoise		' , color: '#00CED1'},
    {name: 'Cadetblue			' , color: '#5F9EA0'},
    {name: 'Steelblue			' , color: '#4682B4'},
    {name: 'Lightsteelblue		' , color: '#B0C4DE'},
    {name: 'Powderblue			' , color: '#B0E0E6'},
    {name: 'Lightblue			' , color: '#ADD8E6'},
    {name: 'Skyblue				' , color: '#87CEEB'},
    {name: 'Lightskyblue		' , color: '#87CEFA'},
    {name: 'Deepskyblue			' , color: '#00BFFF'},
    {name: 'Dodgerblue			' , color: '#1E90FF'},
    {name: 'Cornflowerblue		' , color: '#6495ED'},
    {name: 'Mediumslateblue		' , color: '#7B68EE'},
    {name: 'Royalblue			' , color: '#4169E1'},
    {name: 'Blue				' , color: '#0000FF'},
    {name: 'Mediumblue			' , color: '#0000CD'},
    {name: 'Darkblue			' , color: '#00008B'},
    {name: 'Navy				' , color: '#000080'},
    {name: 'Midnightblue		' , color: '#191970'},
    {name: 'White				' , color: '#FFFFFF'},
    {name: 'Snow				' , color: '#FFFAFA'},
    {name: 'Honeydew			' , color: '#F0FFF0'},
    {name: 'Mintcream			' , color: '#F5FFFA'},
    {name: 'Azure				' , color: '#F0FFFF'},
    {name: 'Aliceblue			' , color: '#F0F8FF'},
    {name: 'Chostwhite			' , color: '#F8F8FF'},
    {name: 'Whitesmoke			' , color: '#F5F5F5'},
    {name: 'Seashell			' , color: '#FFF5EE'},
    {name: 'Beige				' , color: '#F5F5DC'},
    {name: 'Oldlace				' , color: '#FDF5E6'},
    {name: 'Floralwhite			' , color: '#FFFAF0'},
    {name: 'Ivory				' , color: '#FFFFF0'},
    {name: 'Antiquewhite		' , color: '#FAEBD7'},
    {name: 'Linen				' , color: '#FAF0E6'},
    {name: 'Lavenderblush		' , color: '#FFF0F5'},
    {name: 'Mistyrose			' , color: '#FFE4E1'}    
  ];

  constructor() { }

  ngOnInit() {
  }

}
